### ISSUE TITLE
Calling _fff_read and other macros from within a function / accessing a FIFO from other functions

### ISSUE THREAD

**Issue by matlabuser77** [nqtronix/fifofast#2]
I am trying to declare a FIFO in main.c (outside of the main() function as in the fifofast code example), then access that FIFO with functions in other *.c files which are themselves called from main(). I figured out how to get the inline function forms of the fifofast functions working (compiling) in other functions by including a *.h file with the following line:
```
extern volatile fff_proto_t fifo_name;
```
But there's not an inline function for the read macro. I am receiving a compiler error when I attempt to call one of the macro based functions (e.g. _fff_read) from a function, instead of calling directly in main(). 

I'm not sure what I'm doing wrong... What is the proper way to call the fifofast functions from within functions other than main?

On the line that I call _fff_read from within another function, I get this error:
```
[N] 2849 : invalid application of 'sizeof' to an incomplete type 'uint8_t volatile[]'
```
and on line 14 of \fifofast\utility\macros\com\macro_array.h, I get this error:
```
invalid application of 'sizeof' to incomplete type 'volatile uint8_t[] {aka volatile unsigned char[]}'	
```

For what it's worth, I can compile a form of your "minimal code example" in my Atmel Studio 7 C project, albeit with a few warnings.

Something like this works:
```
#include "fifofast.h"
_fff_declare(uint8_t, fifo_name, 16);

int main(void)
{
    volatile uint8_t temp_byte = 0;

    _fff_init(fifo_name);
    _fff_write(fifo_name, 42);

    temp_byte = _fff_read(fifo_name);

    while(1);
}
```

However, I cannot get the macro based fifofast commands to compile when called from within a function.

Something like this yields the above errors:
```
#include "fifofast.h"
#include "misc.h"
_fff_declare(uint8_t, fifo_name, 16);

int main(void)
{
    volatile uint8_t temp_byte = 0;

    _fff_init(fifo_name);
    _fff_write(fifo_name, 42);

    fifo_test();

    while(1);
}
```

Where misc.c:
```
#include "misc.h"

// Simple test function to show the compiler error
void fifo_test(void)
{
    volatile uint8_t    temp_byte = 0;
    temp_byte = _fff_read_lite(fifo_name);
}
```

And misc.h:
```
#ifndef MISC_H_
#define MISC_H_

void fifo_test(void);

#endif
```

 Any insight as to what I'm doing wrong or how to better use this library? Thanks!

**Comment by nqtronix** [comment]
In this libary, each fifo (and it's contents) is stored in its own, custom variable/struct. They are generated each time you use the `_fff_declare` macro (or its variants). 

To access the fifo, its `_id` has to be known in the current scope, which depends on *where* it is declared:

1. **in a .h file:** The fifo can be accessed in all files that include the .h file.
2. **in a .c file**: The fifo can only be accessed within the same .c file.
3. **in a function**: The fifo can only be accessed within the function *and* must be re-initialized the next time the function is called.

Since 0.6.0 pointable fifos are available (suffix `_p`), which allow access by _id and by the pointer value. Note that there is a performance penalty when using pointers, because there are fewer optimisations the compiler can do.

---

**Getting back to your example:** To use the fifo `fifo_name` (renamed to `misc_fifo`) in both `main.c` and `misc.c`, it has to be declared in `misc.h`. For global variables I strongly prefer a prefix with the file name, so I've added `misc_*` to some names.

**main.c:**
```
#include "fifofast.h"
#include "misc.h"    // contains declaration of 'misc_fifo', initialised in the matching .c file

int main(void)
{
    _fff_write(misc_fifo, 42);    // write some data
    misc_fifo_test();    // access data externally

    asm("nop");    // debugger breakpoint
    while(1);
}
```

**misc.c**
```
#include "misc.h"

// initialize the fifo. This line MUST only appear in one .c file
_fff_init(misc_fifo);

// Simple test function
void misc_fifo_test(void)
{
    volatile uint8_t temp_byte = 0;
    temp_byte = _fff_read_lite(misc_fifo);
    asm("nop");    // debugger breakpoint, read temp_byte here
}
```

**misc.h**
```
#ifndef MISC_H_
#define MISC_H_

#include "fifofast.h"    // libary must also be known here to use the '_declare' macro

_fff_declare(uint8_t, misc_fifo, 16);    // declare in .h file to make the fifo a global variable

void misc_fifo_test(void);

#endif
```

---

If you plan on including `misc.h` in many files, consider moving the declaration into a seperate header. This allowes usage of `misc_*` functions, but prevents "unauthorized access" of the fifo itself. Example:

**misc_fifo.h**
```
#ifndef MISC_FIFO_H_
#define MISC_FIFO_H_

#include "fifofast.h"    // libary must also be known here to use the '_declare' macro

_fff_declare(uint8_t, misc_fifo, 16);    // declare in .h file to make the fifo a global variable

#endif
```

**misc_new.h**
```
#ifndef MISC_NEW_H_
#define MISC_NEW_H_

void misc_fifo_test(void);

#endif
```

**misc_new.c**
```
#include "misc_new.h"    // 'misc_*' functions only
#include "misc_fifo.h"    // grant access to the fifo

// initialize the fifo. This line MUST only appear in one .c file
_fff_init(misc_fifo);

void misc_fifo_test(void)
{
    volatile uint8_t temp_byte = 0;
    temp_byte = _fff_read_lite(misc_fifo);
}
```

---

I tested the examples above an they do work in the simulator included in Atmel Studio. Let me know if you still have any issues.

(It is likely using `_fff_init()` in the main function (or any function?) as shown in the readme does not work properly. The simulator does not show correct values, but the generated assembler code might be correct. I'll need to investigate this.)

**Comment by nqtronix** [comment]
>It is likely using _fff_init() in the main function (or any function?) as shown in the readme does not work properly.

On second thought I think the the readme and the demo file were wrong. In my production code I've always put `_fff_init()` outside functions anyway. I've updated both files accordingly.

**Comment by matlabuser77** [comment]
Thank you for the thorough response! Following the above directions fixed my compiler error. I appreciate the detailed assistance.
